# Generated by Django 5.2.9 on 2026-02-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('published_date', models.DateField()),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('SC', 'Science'), ('FN', 'Fun'), ('HC', 'Historic')], max_length=2)),
            ],
        ),
    ]
